---
abstract: 'Interface to Body Mass Index.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Readonly: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Health-BMI
provides:
  Health::BMI:
    file: lib/Health/BMI.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
